### ISSUE TITLE
MIUI11，安卓Q，模块对应的方法无效

### ISSUE THREAD

**Issue by LennoC** [kenvix/miui-df-dferh-01-fix#4]
小米MIX3，MIUI11，安卓Q
permissons下没有对应的google cn配置了，刷入模块抓请求也还是请求的cn域名。

**Comment by RealHeart** [comment]
https://github.com/kenvix/miui-df-dferh-01-fix/commit/a759ef4fb22b9a0925ccc6344662b30fd43519a1

**Comment by LennoC** [comment]
MIX3 最新MIUI11开发。测试没有效果。

**Comment by RealHeart** [comment]
1.尝试清除全部Google类应用数据并重启
